### ISSUE TITLE
Visualise data in bar charts

### ISSUE THREAD

**Issue by b4rdha** [MajaLinder/SEMFIRE#10]
User Story : As a data analyst I want to display a selected dataset in the form of bars, so that I can easily see the categories and their weight in the dataset. The data should be sorted in decreasing order. 

Acceptance Criteria: 
Given a two column dataset, with one column being the categories and the other it’s values, the system should show bars for each of the categorical values set of data in a sorted decreasing order. 

Planning poker score: 21 (0-89 Fibonacci)

**Comment by MalikWaleed3** [comment]
Y axis has been implemented in our project repository. There are two different ways to display the bar charts in splite-bars and stacked, we have set the Stacked bar by default and Y-axis data in numeric type.
