### ISSUE TITLE
Scale labels styling

### ISSUE THREAD

**Issue by arnaudtibco** [MajaLinder/SEMFIRE#100]
Scale labels styling should depend on the Visualizations > Canvas styling > Edit custom theme > Details > Visualization general font setting

**Comment by b4rdha** [comment]
Planning poker score: 3 (0-89 Fibonacci)

**Comment by b4rdha** [comment]
Add bar label to be rendered under the same fashion as provided[ template](https://www.figma.com/file/hhrTwWhAiTzyvPrGqTCaA7/Untitled?node-id=0%3A1)
Use settings interface to pass the same styling as framework, add more settings if needed.

**Comment by inquisition** [comment]
Yes. The scales lines color should not be based on the font color but on the line styling. It seems to be available from the API. Same for tick marks.

![Screenshot 2022-12-01 at 09 14 44](https://user-images.githubusercontent.com/692801/205000849-d9351b5f-55d1-4103-b834-505fa41d12e0.png)
