### ISSUE TITLE
Drag & drop labels

### ISSUE THREAD

**Issue by arnaudtibco** [MajaLinder/SEMFIRE#101]
When drag & dropping a column to the visualization, the labels should respect the axis names.
- X-axis: Use '{Column Name}' on the category axis (vs Use '{Column Name}' on the mod's X-axis)
- Y-axis: Use '{Column Name}' on the value axis (vs Use '{Column Name}' on the mod's Y-axis)

![Screenshot 2022-11-18 at 13 51 28](https://user-images.githubusercontent.com/15086293/202710358-2fe35e6c-755b-40d9-a1b9-65736ab41e13.png)

**Comment by b4rdha** [comment]
Planning poker score: 1 (0-89 Fibonacci)
