### ISSUE TITLE
Marking support on bars

### ISSUE THREAD

**Issue by arnaudtibco** [MajaLinder/SEMFIRE#102]
The experience should be the same as the Spotfire bar chart.

If no color by or single color:
- User must be able to mark a bar by clicking on a bar
- User must be able to mark multiple bars by clicking on bars while holding a key
- User must be able to mark multiple bars by drawing a rectangle selection
- User must be able to unmark a bar by clicking outside bars

If color by axis set:
- User must be able to mark a bar segment by clicking on a segment
- User must be able to mark multiple bar segments by click on segments while holding a key
- User must be able to mark multiple segments by drawing a rectangle selection
- User must be able to unmark segments by clicking outside bars

See [Spotfire document about marking](https://docs.tibco.com/pub/sfire-analyst/latest/doc/html/en-US/TIB_sfire-analyst_UsersGuide/index.htm#t=vis%2Fvis_marking_in_visualizations.htm)

**Comment by b4rdha** [comment]
Planning poker score: 8 (0-89 Fibonacci)

**Comment by b4rdha** [comment]
Dependent on #99
