### ISSUE TITLE
Mouse over support for bars

### ISSUE THREAD

**Issue by arnaudtibco** [MajaLinder/SEMFIRE#103]
Hovering a bar or segment should display a highlight border similar to the bar chart.

![Screenshot 2022-11-18 at 14 05 22](https://user-images.githubusercontent.com/15086293/202712043-74cfcf4d-3da1-41be-a6c0-daee80e6e374.png)

**Comment by b4rdha** [comment]
Planning poker score: 3 (0-89 Fibonacci)

**Comment by b4rdha** [comment]
Dependent on #99
