### ISSUE TITLE
Flexible scale labels

### ISSUE THREAD

**Issue by arnaudtibco** [MajaLinder/SEMFIRE#105]
Augmenting the number of categories in the Category Axis or resizing the width of the chart makes the labels overlap and unreadable. Not sure what is the best method.

**Comment by MajaLinder** [comment]
![Image](https://user-images.githubusercontent.com/63287192/203003241-3168e582-19ac-427c-9a41-b88516e1bc61.png)

**Comment by b4rdha** [comment]
Planning poker score: 8 (0-89 Fibonacci)

**Comment by LIYUHAN22** [comment]
I have looked at areachant's code, it also looks not so good, but it have a small popup when mouse put on it.

![Image](https://user-images.githubusercontent.com/102019782/204156107-3e363acf-b881-45f9-b343-52ed3c303906.png)

**Comment by LIYUHAN22** [comment]
![Image](https://user-images.githubusercontent.com/102019782/205666187-a7cb11f9-0836-4816-b687-ac6459a13f98.png)



![Image](https://user-images.githubusercontent.com/102019782/205666341-2267d6bc-aeeb-41ed-9248-0ea86a973dcd.png)



![Image](https://user-images.githubusercontent.com/102019782/205666785-6fa041c0-78f8-40af-afb2-fd73f04c51ec.png)
