### ISSUE TITLE
Calculate cumulative value

### ISSUE THREAD

**Issue by b4rdha** [MajaLinder/SEMFIRE#12]
User Story : 
As a data analyst I want to be able to view a line of the cumulative values of the categories, so that I can understand the contribution factors by size and group. 

Acceptance Criteria: 
Given a sorted dataset with two columns, one being the categories and the other its values, the system should calculate its cumulative value point and display it on the x,y axis in the shape of a line. 

Planning poker score: 34 (0-89 Fibonacci)

**Comment by LIYUHAN22** [comment]
![Image](https://user-images.githubusercontent.com/102019782/194237246-455d8e98-b64b-4ba8-bf0a-62f78948d276.png)
