### ISSUE TITLE
Display axis for data visualization

### ISSUE THREAD

**Issue by b4rdha** [MajaLinder/SEMFIRE#16]
User Story: As a data analyst I want to be able to see the axis for displaying my data, so that I can understand the projection in respect to the x and y axis. 

Acceptance Criteria: 
When one dataset is provided and the Pareto chart mod has been selected: 
The system should show:

- [x]  a vertical y (original) axis with numerical values 
- [x] a horizontal x axis with categorical values.
- [x] another vertical y axis displayed parallel to the original y- in the right side of the screen, with percentages as values. 

Planning poker score: 21 (0-89 Fibonacci)

**Comment by MalikWaleed3** [comment]
In order to use import and export functions in order classes, we have used the Bundle.js library, [](https://www.npmjs.com/package/bundle-js). This issue has been resolved now in my main template.

**Comment by gusmalikah** [comment]
The CSS has been changed from absolute positioning to Flex Box. This is done because it provide more flexibility and scaling of Div can be done easily.

**Comment by gusmalikah** [comment]
In methods.js file tick = createDiv("tick", "") is added to add a small line side with the values as shown in our prototype. The percentage sign is also added on the Z scale following the prototype.

**Comment by gusmalikah** [comment]
The responsiveness is tackled with following CSS properties: 
    max-width: 800px;
    width: 78vw;
This how the Z-Scale can almost be seen all the time except less then 500px width which is mobile screen and ignored.

**Comment by AstridBer** [comment]
The 3 tasks are finished and acceptance criteria met
