### ISSUE TITLE
Adjust marking border in dark mode

### ISSUE THREAD

**Issue by arnaudtibco** [MajaLinder/SEMFIRE#178]
Currently the marking border is black even if dark mod is enable. Would be nice to turn that to white to better see it.

![Screenshot 2022-12-15 at 10 24 00](https://user-images.githubusercontent.com/15086293/207822104-3d1b6892-5af5-4a16-8eb1-c9046c75a5bb.png)

![Screenshot 2022-12-15 at 10 23 56](https://user-images.githubusercontent.com/15086293/207822121-fe516798-0696-4b03-abbc-9ecdeadc4529.png)

**Comment by MajaLinder** [comment]
This also applies to hovering on line markers (merged to main) and hovering the 80% line (in progress)

**Comment by MajaLinder** [comment]
Fixed in this PR https://github.com/MajaLinder/SEMFIRE/pull/183
