### ISSUE TITLE
Marking bug

### ISSUE THREAD

**Issue by MajaLinder** [MajaLinder/SEMFIRE#182]
After clicking on the 80% line and changing the category data, the markings are left and not properly selected.

![Image](https://user-images.githubusercontent.com/63287192/207851524-1111925b-69d2-4974-acf9-42514bd585be.png)

**Comment by AstridBer** [comment]
The behavior is the same if you mark a bar or line marker and then change category

**Comment by MajaLinder** [comment]
I tested this with Spotfire's barchart and it actually has the same behaviour, so I don't think we need to take care of it.
