### ISSUE TITLE
Initial prototype

### ISSUE THREAD

**Issue by b4rdha** [MajaLinder/SEMFIRE#2]
Provide a prototype of the solution using a preferred tool for UI prototying. 

User story: 
As a data analyst, I want to be able to display my data in a Pareto chart style, so that I can easily analyse the biggest impact factor (80/20 rule). 

Acceptance criteria: 
The prototype should include visual representation of bar charts sorted in descending order, as well as a cumulative sum line.

**Comment by np9693** [comment]
A prototype for demonstrating a bar chart in descending order and cumulative sum as a line.
Figma file link: [Figma](https://www.figma.com/file/XpMZ5jDU9X18MswcZ80jfH/SEMFIRE?node-id=25%3A273)
**_Design Elements used as per Tbico design system:_**
1. Colors
2. Typography
3. Grid system

**_Different states of the chart:_**
- Success state 
![Image](https://user-images.githubusercontent.com/70427158/190970182-1cdbfa96-ed00-4116-b4d5-12ec6154d85b.png)
- Hover State
![Image](https://user-images.githubusercontent.com/70427158/190970264-1cde0e34-351f-4b56-a993-311d22c7c8d7.png)
- Selected(clicked on the bar or line) state
![Image](https://user-images.githubusercontent.com/70427158/190970400-a19a5a51-f836-4130-8827-f81c58509715.png)

**_Design documentation from the research:_**
[Design Documentation](https://docs.google.com/document/d/1f33Gi7tIQB_o0O55H-cO995THMvJoA63oY4BPzWFqDw/edit?usp=sharing)

**Comment by np9693** [comment]
Canvas Styling from Tibco Spotfire Analyst:

**_Open a visualization you want, now follow these steps:_**

**Step 1:** Select Visualizations --> Canvas Styling --> Edit custom theme
![Image](https://user-images.githubusercontent.com/70427158/190983992-19fefb9c-98b1-4987-881c-87066066f298.png)
**Step 2:** You should be able to see this wizard 
![Image](https://user-images.githubusercontent.com/70427158/190984252-0924a9e8-bd75-4284-aa37-03d79890ebc1.png)
**Step 3:** Let's try to change the background for the visualization you are viewing now. 
![Image](https://user-images.githubusercontent.com/70427158/190984518-ad086eb1-cf00-4451-8083-ad1ff573c54f.png)
**Step 4:** The background has been changed to a new color
![Image](https://user-images.githubusercontent.com/70427158/190984758-6c63b67c-4c5f-4ff5-9a40-2e488314bad2.png)
**Other styling options that can be customized in Custom theme wizard:**
Fonts style
Font size
Font colors
Annotation styling
Margins
Paddings
Scales styling

**Comment by MajaLinder** [comment]
Great work and documentation, Navya! Looks good to me as a first prototype.

**Comment by np9693** [comment]
The acceptance criteria for this issue from Sprint 1 is done. Documentation related to this is also updated. A detailed guide for canvas setting from Spotfire has also been documented for future use.
