### ISSUE TITLE
Draw a Component Diagram

### ISSUE THREAD

**Issue by b4rdha** [MajaLinder/SEMFIRE#27]
Draw a component diagram to capture requirements for the project

**Comment by MajaLinder** [comment]
Link the the component diagram https://app.diagrams.net/#G1gbPmP3E52N9oNEx1uR6Chc9TlyOKqJn-

**Comment by LIYUHAN22** [comment]
![Image](https://user-images.githubusercontent.com/102019782/207652670-6e52d33e-e2b3-45f8-84f8-ef44ae7e3ac5.png)

https://drive.google.com/file/d/1fwBp6SkDaLxX-vXZc1RotOqV5wFBCbxk/view?usp=sharing
