### ISSUE TITLE
Mod API research

### ISSUE THREAD

**Issue by b4rdha** [MajaLinder/SEMFIRE#3]
This link https://tibcosoftware.github.io/spotfire-mods/docs/using-the-api/api-docs/ provides the API documentation which will help us understand the working of the API along with it lists all the interfaces and the functions in the API. Each interface and function has a short introduction and how to use them.

**Comment by MalikWaleed3** [comment]
In order to use import and export functions in other files, we have used the Bundle.js library, [Bundle.js Website](https://www.npmjs.com/package/bundle-js) This issue has been resolved now in my main template.
