### ISSUE TITLE
Adjust Category Display

### ISSUE THREAD

**Issue by b4rdha** [MajaLinder/SEMFIRE#36]
Current display for category names is not properly showing tags when more categories visualised. (for reference see image below). 

To do: fix overlapping to display category tags in a readable fashion. 

Acceptance criteria: When multiple categories are selected, the category titles should remain readable. 

![Image](https://user-images.githubusercontent.com/81046735/193539796-d6dbfcaa-5d22-4af3-9766-f242bb0fc9cc.png)

**Comment by gusmalikah** [comment]
Now the overlay is gone and the names are displaying in the center of the bars.
If the bars names need space then the text hide only showing the first charecters of the name.
