### ISSUE TITLE
Adjust categories to align with the bars

### ISSUE THREAD

**Issue by MajaLinder** [MajaLinder/SEMFIRE#39]
There is an issue with the alignment of the categories in comparision with the bars.
There should be ticks on the x-axis to separate the categories.

![Image](https://user-images.githubusercontent.com/63287192/193810051-3a159637-72c7-4a28-8123-5384c41182c3.png)

**Comment by np9693** [comment]
- Alignment of the bars and categories has been fixed now, where the name of the category is aligned in the center of the bar.
- Ticks between the categories have been fixed


![Image](https://user-images.githubusercontent.com/70427158/194025564-26864b2e-4f0f-4f12-bd25-ed1aeca77d7d.png)

**Comment by np9693** [comment]
- Overflowing of the category names has been fixed, and now it stays between each bar as shown in the picture below.

![Image](https://user-images.githubusercontent.com/70427158/194026705-eadf7079-7f3a-4797-b223-87fd677b8592.png)
