### ISSUE TITLE
Pareto chart and current mod options

### ISSUE THREAD

**Issue by b4rdha** [MajaLinder/SEMFIRE#4]
Research to understand and break down requirements

**Comment by AstridBer** [comment]
How to create a pareto chart using the combination chart: 
https://community.tibco.com/s/article/configuring-combination-chart-pareto-chart

**Comment by AstridBer** [comment]
Documentation on custom expressions: https://docs.tibco.com/pub/spotfire/7.0.0/doc/html/ncfe/ncfe_custom_expressions_introduction.htm ‘

**Comment by AstridBer** [comment]
Examples of various Pareto charts and their options
https://docs.google.com/document/d/10-b6_CbE1XeSNSrOqXl4RFZ-5T9pvFfBJ3yqUiTee_U/edit?usp=sharing
