### ISSUE TITLE
Adjust bar spacing

### ISSUE THREAD

**Issue by b4rdha** [MajaLinder/SEMFIRE#44]
For the first and last bars, spacing needs to be equally distant from origin (same as space between all bars) 
For exact spacing see Spotgire figma prototype. 

Acceptance criteria: First and last bar are spaced from the axes in the same distance as Spotfire prototype. 
Adjusting should remain responsive (maintain the same distance) when changing screen size up until 450px. 

Planning poker score: 13 (0-89 Fibonacci)

**Comment by np9693** [comment]
**The spacing between bars has been solved.**


![Image](https://user-images.githubusercontent.com/70427158/195651536-786a58c7-18ff-44fc-b324-c8972d3edad3.png)
![Image](https://user-images.githubusercontent.com/70427158/195651537-681fcc42-06c8-4faa-927d-1686c6675aef.png)

*note: More reference pictures are attached in this pull request #61

**Comment by b4rdha** [comment]
The issue is obsolete in the new code refactor and handled in D3 instead.
