### ISSUE TITLE
Use Case diagram

### ISSUE THREAD

**Issue by b4rdha** [MajaLinder/SEMFIRE#5]
Draw an initial use case diagram, capturing requirements as provided [here](https://docs.google.com/document/d/1Z4Xk4tLdnozC05QHcFjhKHd9OH0BG5GqvuNAYMkXPQc/edit#) and [here](https://docs.google.com/document/d/1ffAYuGLEWo3f_LT9AGrHyCGOFvE6tTXqLCTzGyRJUSM/edit)

**Comment by AstridBer** [comment]
Draft of use case diagram can be found in the diagrams folder in our shared drive
