### ISSUE TITLE
Adjust cumulative line

### ISSUE THREAD

**Issue by b4rdha** [MajaLinder/SEMFIRE#54]
Adjust the display. of cumulative line so that the data is readable. Current display is not correct (se reference picture). 

Acceptance criteria: 

- [ ] The cumulative line starts to display in the middle of the first bar and ends in the midpoint of the last bar. 
- [x] The cumulative line should remain responsive for screen size 450px and above. 

![Image](https://user-images.githubusercontent.com/81046735/195022934-d9adc034-0285-44b8-a5e2-3d42e5eaf074.png)

**Comment by MajaLinder** [comment]
The responsiveness is done, meaning that the line doesn't go outside of the chart. 
We are facing some challenges, and would like guidance from Tibco, when adjusting the line so that it starts and ends in the middle of the first and last bars.

**Comment by MajaLinder** [comment]
The responsiveness is done, meaning that the line doesn't go outside of the chart. 
We are facing some challenges, and would like guidance from Tibco, when adjusting the line so that it starts and ends in the middle of the first and last bars.

**Comment by b4rdha** [comment]
The issue is obsolete in the new code refactor and handled in D3 instead.
