### ISSUE TITLE
Adjust naming with Tibco requests

### ISSUE THREAD

**Issue by b4rdha** [MajaLinder/SEMFIRE#62]
package.json

- [x]  Version: 0.1.0
- [x]  Descriptions? 
- [x] Is there only dev dependencies? Any dependencies that are not dev?

mod-manifest.json

- [x] Version: 0.1.0
- [x] Id: sfire-mods-pareto
- [ ]  icon

Planning poker score: 2 (0-89 Fibonacci)

**Comment by LIYUHAN22** [comment]
Icon part has made a new card
