### ISSUE TITLE
Update Use Case diagram

### ISSUE THREAD

**Issue by MajaLinder** [MajaLinder/SEMFIRE#72]

**Comment by MajaLinder** [comment]
https://app.diagrams.net/#G1gAkwN2eIkhNvo9QKSAsK4_vq9yuNkCe1

**Comment by b4rdha** [comment]
nice job updating it please add it to the repo as well, and let's try to use it on monday when we plan the sprint

**Comment by MajaLinder** [comment]
@b4rdha I'm still a little uncertain about this. Did you think it was fine to leave some of the cases uncolored? I'm also not sure if all the MVP/green colored ones were actually planned for the MVP, and how many "additional features" should be added in this update
