### ISSUE TITLE
Visualization size

### ISSUE THREAD

**Issue by arnaudtibco** [MajaLinder/SEMFIRE#97]
The visualization size should be similar to a bar chart visualization.

![Screenshot 2022-11-18 at 13 35 43](https://user-images.githubusercontent.com/15086293/202706701-b7652214-baef-42bd-bbbb-274d976c50ff.png)

**Comment by b4rdha** [comment]
Planning poker score: 1 (0-89 Fibonacci)

**Comment by MajaLinder** [comment]
On hold until we get:
- Tibco's margins
- Answer from developers regarding the use of windowSize
